export const SHOW_ALL_PRODUCTS = "SHOW_ALL_PRODUCTS";
export const ADD_PRODUCT_TO_LIST = "ADD_PRODUCT_TO_LIST";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

//Fetch Specific Product
export const FETCH_SPECIFIC_PRODUCT = 'FETCH_SPECIFIC_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';

